name: xvec_dev
channels:
  - conda-forge
dependencies:
  - python
  # required
  - shapely=2
  - xarray
  - rioxarray=0.14.1
  - joblib=1.3.2
  - rasterio=1.3.8
  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  # documentation
  - sphinx
  - myst-nb
  - sphinx-copybutton
  - numpydoc
  - geopandas
  - pyarrow
  # linting
  - ruff
  - black
  - pip
  - pip:
      - sphinx_autosummary_accessors
      - sphinx-book-theme
      - geodatasets
