name: xvec_dev
channels:
  - conda-forge
dependencies:
  - python
  # to build from source
  - cython
  - geos
  - proj
  - rioxarray=0.14.1
  - joblib=1.3.2
  - rasterio=1.3.8
  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-reportlog
  - geopandas-base
  - pip
  - pip:
      - git+https://github.com/shapely/shapely.git@main
      - git+https://github.com/pydata/xarray.git@main
      - git+https://github.com/pyproj4/pyproj.git
